name: "Update Zed packages ❄️"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 0" # https://crontab.guru/#0_10_*_*_0
jobs:
  update-packages:
    runs-on: nixos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@latest
      # - name: Install Nix
      #   uses: cachix/install-nix-action@v31
      - name: Update flake packages
        uses: selfuryon/nix-update-action@v1
